### ISSUE TITLE
setting screen to allow storing of REST url

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#160]
- [x] update wireframes
- [x] input field (no input field)
- [x] setting page
- [x] persist setting 
- [x] page layout 
- [x] update login screen
- [x] navigate to settings via popover 
- [x] create storage service
- [x] unit test
  - [x] home: popover gets called
  - [x] login: setting read from storage
  - [x] popover: button leads to setting
- [x] e2e testing

**Comment by sandrozbinden** [comment]
- [ ] input field
- [  ]setting page
- [ ] persist setting 
- [ ] page layout 
- [ ] update login screen
