### ISSUE TITLE
wireframes: add error messages

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#177]
> Wenn Gruppen nicht berechtigt ist um Art oder Fall zu erstellen soll eine Fehlermeldung erscheinen. Ev. auch noch in Wireframe oder in Text dazu aufnehmen.
> Screens für Error Handling nicht vergessen

add a single screen for
- [x] a error
- [x] a notification

**Comment by mleu** [comment]
Added two new wireframe pages "FallListeAktivitätAbgeschlossen" for a notification example and  "FallListeAktivitätFehler" as a error example.
Please review.

**Comment by nikaluus** [comment]
Looks good. Nice work
