### ISSUE TITLE
wireframes: explain metadata default values

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#178]
> MehrfachbildMetadaten: Verstehe nicht, wie man die MetaDaten für mehrere Bilder gleichzeitig erstellen kann.

**Comment by mleu** [comment]
Added Comment to wireframe pages "MehrfachbildMetadaten2, ""MehrfachbildMetadaten3",  "MehrfachbildMetadatenOhneSchuhe". Please review.

**Comment by sandrozbinden** [comment]
Looks great thanks a lot
