### ISSUE TITLE
sad: explain dynamic meta model and where the data itself fits in

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#179]
> Wo ist das Datenfeld für das Bild?

- [ ] bring clarity to the difference between the meta model and the data itself

> Würde die IMS Schnittstelle die Struktur der Daten ausliefern, könnte man die Struktur in der App generisch machen und die App würde sich dem entsprechenden Bereich anpassen. Ist nur so eine Idee und noch nicht ganz fertig durchdacht.

- [ ] describe the dynamic nature of the API

**Comment by sandrozbinden** [comment]
It should clear that ims is  asystem for multiple archive types. Thus we don't need a more specific description of the meta model possibilities
