### ISSUE TITLE
wireframes: show structure depth

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#189]
> FA9 Strukturtiefe: Wo sehe ich Strukturtiefe in Wireframes?

add description to Fall Liste that these are the structures

**Comment by mleu** [comment]
Added Comment to wireframe page "Fall Liste", please review.

**Comment by sandrozbinden** [comment]
Change "werdet mit Attributen aus ihren Eltern-Tabellen angereichert" to "können mit Attributen aus ihren Eltern-Tabellen angereichert werden."
