### ISSUE TITLE
update ionic to 3.0

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#190]
**Timebox 3 hours**

http://blog.ionic.io/ionic-3-0-has-arrived/
- [x] Coverage Issues needs to be resolved (new http injection mechanism lead to not execution of observables)
  - Coverage was very low https://coveralls.io/builds/11193318
  - and increased when going back to ionic v2: https://coveralls.io/builds/11194348
  - opened new issue for lower coverage of mock responses #292 
- [x] Fix dependecies issue  or revert so that task does not fail

- [x] Update ionic cli do no longer  pin to specific version …

**Comment by sandrozbinden** [comment]
Delete node_modules and then execute npm install
