### ISSUE TITLE
Remove coverage deprecation warning

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#214]
**Timeboxed 1 hour**
The problem might be an not uptodate karma-webpackage transitive dependecies.

The transitive dependecies loader-utils should be updated 

- [ ] Create issue in karma-webpack

node:10896) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

**Comment by mleu** [comment]
Webpack has loaders, which are defined in `test-config/webpack.test.js`. These in turn may use loader-utils, which is deprecating certain functions as described in the link above (issue 56).

We currently use two loaders which have not managed to fix this yet:
- **angular2-template-loader**
  relevant line: https://github.com/TheLarkInn/angular2-template-loader/blob/master/index.js#L21
  PR: 61 (still open)
- **istanbul-instrumenter-loader**
  relevant line: https://github.com/webpack-contrib/istanbul-instrumenter-loader/blob/master/index.js#L15
  PR: 47 (still open)

We will have to live with this until both PRs get merged.

**Comment by sandrozbinden** [comment]
Could you attach the pull requests. Maybe we can remember them that it is an important issue for our project.
