### ISSUE TITLE
Add Codelyzer for ng lint

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#323]
There are anguler specific lint that would check for kebab case to avoid issues like #271

https://github.com/mgechev/codelyzer

- [ ] secondary lint must be configured but without error

Fixing of issues might no be part of this story

**Comment by nikaluus** [comment]
- [ ] Codelyzer added
- [ ] Documentation updated
- [ ] TSlint loader added
- [ ] Enable typechecking
