### ISSUE TITLE
upload with correct name of file

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#378]
remove static `SmartPhonePhoto.jpg` name
but is it really needed?
filename may look like `file.jpg?123` on android from cordova, which IMS does not like

Others do it like this: https://devdactic.com/ionic-2-images/#crayon-593a3ef1a04a9543122189

Ask imagic, which is the desired solution

**Comment by sandrozbinden** [comment]
pic and imagic aggreed that for mobile devices the name is not relevant. it is important that no errors appear when uploading files with same name which is already handled by ims
