### ISSUE TITLE
publish to app and play store

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#402]
- [x] publish to play store
- [x] publish to app store

Steps for uploading ipa to app store:
1. use `ionic package build ios --profile prod --release --prod`
2. start Applicatoin Loader on MacOS
3. **doubleclick** on big gray "A" icon and select .ipa
4. if reuploading same version: add a incrementing second version number in `config.xml`: https://cordova.apache.org/docs/en/4.0.0/config_ref/index.html#additional-versioning

**Comment by mleu** [comment]
Submitted to both stores 🎉
