### ISSUE TITLE
create steps to create document collection for hsr

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#433]
index, talk with susanne (cd, upload), export from github (mardown to html), add external documents describe how to do it

index has to contain every important document that should be evaluated by advisor

> Für die Abgabe per 28.8. möchten wir dir gerne die Dokumente in folgendem Format übermitteln:
> 
>     ZIP File per Mail oder Moodle Upload
>     Inhaltsverzeichnis in Form einer HTML-Datei mit Links auf die Dokumente
>     Dokumente als HTML Dateien
>     Bilder als PNG/JPEG, eingebettet in den HTML-Dokumenten
>     Zeiterfassungs-Tabelle entweder als HTML-Datei, PDF oder Excel.
> 
> Sprich keine Word oder PDF Dokumente welche fürs Ausdrucken optimiert wären.
> Ausser natürlich den Bericht für die Publikation, den werden wie wie gewünscht als publikation.pdf einreichen.
> 
> Das Abstract senden wir per Mail.

- [x] automatically gereate html 
- [x] check for broken links
- [x] burnup chart -> where should we add the burn up
- [x] link closed issues per sprint  in sprint overview page 
- [ ]  storymap =>  replace http link with the exported image version or let it like it is no?
- [x] src / e2e / script => should there be a link to it
- [x] index / README.md => should we have an Introduction text in the home page
- [ ] get exception for logo from advisor and sign Eigenständigkeitserklärung
 
Use  https://github.com/joeyespo/grip as it has the best output when creating the final document collection

**Comment by sandrozbinden** [comment]
To check for broken links install

npm install http-server -g
npm install broken-link-checker -gn
cd document-collection
http-server
blc http://localhost:8080/README.html -ro > broken_links.txt 

and then check the created broken_links txt for broken links :)

**Comment by mleu** [comment]
burnup image could be shown directly on `docs/sprints.md`
a snapshot of the storymap at the end of sprint 13 could be shown as a example in the chapter "story map" in the projectplan.
a link to code is not needed in my opinion
small introductory text would be nice, could be done when we have spare time (optional)
