### ISSUE TITLE
final explorative test session

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#435]
- [x] discuss mob test session
- [ ] describe explorative test session in project plan (refactor chaptor manual testing )
- [x] convert raw data to html, fix typos notes and add to repo

**Comment by sandrozbinden** [comment]
Input Link from Advisor that might can help https://www.hsr.ch/de/weiterbildung/technik-und-it/praesentationen-der-master-arbeiten/

**Comment by mleu** [comment]
raw data uploaded to gdrive as "Explorative Test Session Data.zip"
