### ISSUE TITLE
Fix Lint issues

### ISSUE THREAD

**Issue by nikaluus** [IMSmobile/app#436]
All activation in own pr

Checked means pr exists

- [x] activate rules that can be easly activated
- [x] activate lint rule "member-access": [true, "check-accessor"]
- [x] activate lint rule  "no-any": true, @sandrozbinden  #492
- [x] activate lint rule "typedef": [true, "call-signature", "parameter", "member-variable-declaration"],
- [x] activate lint rule "only-arrow-functions": [true],
- :x: activate lint rule "no-empty": true, => won't fix as it is a vaild use case in tests
- [x] activate lint rule "no-string-literal": true
- [x] activate lint rule "restrict-plus-operands": true,
- [x] activate lint rule "triple-equals": true,
- [x]  activate lint rule "max-file-line-count": [true, 200],
- [x] activate lint rule "no-consecutive-blank-lines": true,
- [x] activate lint rule "object-literal-key-quotes": [true, "consistent-as-needed"],
-  :x: activate lint rule "object-literal-shorthand": true
- [x] activate lint rule "ordered-imports": [true],
- [x] activate lint rule "variable-name": [true],
- [x] activate lint rule  "no-unnecessary-callback-wrapper": true,
- [x] activate lint rule  "no-boolean-literal-compare": true,
- [x] activate lint rule "no-magic-numbers": true,
- [x] activate lint rule "prefer-const": true,
- [x] activate lint rule "prefer-for-of": true,
- [x] activate lint rule "unified-signatures": true,
- [x] activate lint rule "no-duplicate-super": true,
- [x] activate lint rule "prefer-template": [true, "allow-single-concat"],
- [x] activate lint rule "arrow-return-shorthand": true,
- [x] activate lint rule "no-null-keyword": true,
- [x] activate lint rule "strict-boolean-expressions": true,
- [x] activate lint rule  "typeof-compare": true,
- [x] activate lint rule "no-object-literal-type-assertion": true,
- [x] activate lint rule "cyclomatic-complexity": [true],
- [x] activate lintrule "no-unused-variable": true
-  [x] check maybe disabled lint checks because we no longer use ionic app script
-  [x] **timeboxed 1h** research why some rules are not available
 - [x] activate lintrule  "arrow-return-shorthand":  with "multiline"

**Comment by sandro** [comment]
@nikaluus hey, I'm `@sandro`. I don't think I'm due any credit here, try `sandrozbinden`

**Comment by nikaluus** [comment]
(Nearly) all lint rules implemented. New Issue created for "no-any" #492
