### ISSUE TITLE
npm run release improvements

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#440]
- [x] fix tag propagation:
  - [x] disable tagging in config
  - [x] emit message to not forget to add tag manually to release commit
- [x] reference our rules in changelog.md (currently the text refers to standard-commit rules.) split into #448

**Comment by sandrozbinden** [comment]
the headers changelog that contains a reference to the standard version guidelines can't currently be changed there is an issue here https://github.com/conventional-changelog/standard-version/issues/171 but no action currently. Suggestion split the item and  make reference our rules in changelog.md  a single item
