### ISSUE TITLE
sad: create dataflow diagram

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#481]
similar to course on architecture (apple & oranges).

```
--> Image data  (Camera|Gallery|Files)      \
                                                --> Upload
--> Metadata                                /
```

get feedback from advisor as soon to ask if it goes into the right direction

Actual state saved unter gdrive/Masterarbeit/Diagramme/Dataflow Diagram

**Comment by nikaluus** [comment]
![20170725_2212807.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e16d5601550f130005f4f1/125516c66e82c728ace21e0d46bac4cb74d2d4fbdad6ed11f50fa8c47e046b313916ac217586f76ae5002e590e0918f8480a5e15afa88c79afb73c70df5f5fe4843f4d68d47f40f2ecdd42e64bef62994597b4ba804dc5e83c25e68f8f473918041d9bb2.jpg)
