### ISSUE TITLE
fill archives with valid keywordfield example data on server

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#507]
- [x] Possiblity to add keywords. -> seeting has been wrongly migrated.

Medicine
I_BodyPartEx => https://sinv-56028.edu.hsr.ch/rest/keywordcatalogs/4

Police
KeywordSingleI =>https://sinv-56028.edu.hsr.ch/rest/keywordcatalogs/90
KeywordDual	=>  https://sinv-56028.edu.hsr.ch/rest/keywordcatalogs/1

**Comment by mleu** [comment]
Good read-world examples, thanks!
