### ISSUE TITLE
prepare retro in new style

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#548]
With Retromat: https://plans-for-retrospectives.com/en/

(This link was here for some reason: ~~https://plans-for-retrospectives.com/en/?id=108-116-41-39-60~~)

**Comment by sandrozbinden** [comment]
Suggested retro for next sprint https://plans-for-retrospectives.com/en/?id=82-126-8-11-104

**Comment by mleu** [comment]
I browsed thru some other suggestions to get a feeling of the choices.
Your suggestion seems like a good fit for our small team plus does not need a lot of gadgeds and preparation.
Well done! 👍
