### ISSUE TITLE
Order and Setup Virtual Machine

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#6]

**Comment by mleu** [comment]
Access problems, asked support via email.

**Comment by mleu** [comment]
VM has been redeployed, access works now

**Comment by sandrozbinden** [comment]
We might need to extend disk space. As we are working with images 40gb (including sql server, ims server and os might fill up quickly

**Comment by mleu** [comment]
Asked for 10-20 GB more space

**Comment by mleu** [comment]
Got 20 GB more disk, we now need to expand the filesystem in diskmanager somehow

**Comment by mleu** [comment]
C: drive expanded
