### ISSUE TITLE
setup installation app on iphone and android online or from windows pc

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#99]
we want to streamline the installation process for sprint review demos
- https://docs.ionic.io/tools/view/
- http://view.ionic.io/

- [x] setup ionic view
- [x] test with iOS
- [x] test with android
- [x] research different channels to split devs and stakeholder view versions
- [x] ask ionic aboutch different channels (to tag production and to tag dev)
  - [x] got feedback, this is currently not supported, may be in the future
- [x] decide which direction we want to go: **we will use ionic view for development**

-  ~~do a `ionic upload` on merge into `master` on new branch~~
```
if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  npm run ionic:build && ionic upload
  rc=$?
fi
exit $rc
```
- [ ] update readme.md: document as manual testing

**Comment by mleu** [comment]
asked ionic about different channels for Ionic View: https://ionic.zendesk.com/hc/en-us/requests/1190
